<?php
/**
 * @var $block \Swarming\SubscribePro\Block\Product\Subscription
 */
?>

<div class="subscription-container" data-bind="scope: 'subscription-container'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }
    }
</script>
