<?php
/** @var \Swarming\SubscribePro\Block\Cart\Subscription $block */
/** @var \Magento\Framework\Escaper $block */
?>
<div class="subscription-container" data-bind="scope: 'subscription-container-<?= (int)$block->getItem()->getId() ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
        }
    }
</script>
