<?php
/** @var \Swarming\SubscribePro\Block\Vault\AddButton $block */
?>
<div class="actions vault-list-action">
    <button class="action primary"
            data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl(
                $block->getUrl('swarming_subscribepro/cards/new')
            ) ?>"}}'
            type="button" title="<?= $block->escapeHtmlAttr(__('Add New Card')) ?>">
        <span><?= $block->escapeHtml(__('Add New Card')) ?></span>
    </button>
</div>
