<?php
/** @var \Swarming\SubscribePro\Block\Vault\AddButton $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="actions vault-list-action">
    <button class="action primary"
            data-mage-init='{"redirectUrl":{"url":"<?= $escaper->escapeUrl($block->getUrl('swarming_subscribepro/cards/new')) ?>"}}'
            type="button" title="<?= $escaper->escapeHtmlAttr(__('Add New Card')) ?>">
        <span><?= $escaper->escapeHtml(__('Add New Card')) ?></span>
    </button>
</div>
