<?php

use Magento\Vault\Api\Data\PaymentTokenInterface;

/** @var \Swarming\SubscribePro\Block\Vault\CardRenderer $block */

$ccNumberView = $block->escapeHtml($block->getNumberLast4Digits());
?>
<tr>
    <td data-th="<?= $block->escapeHtml(__('Card Number')) ?>" class="col card-number">
        <span><?= $block->escapeHtml(__('ending')) ?></span> <?= /** @noEscape */ $ccNumberView ?>
        <?php if ($block->isPending()): ?>
            <sub class="card-pending"><?= $block->escapeHtml(__('pending')) ?></sub>
        <?php endif; ?>
        <?= $block->escapeHtml($block->getApplePayLabel()) ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Expiration Date')) ?>" class="col card-expire">
        <?= $block->escapeHtml($block->getExpDate()) ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Type')) ?>" class="col card-type">
        <img src="<?= /* @noEscape */ $block->getIconUrl() ?>"
             width="<?= /* @noEscape */ $block->getIconWidth() ?>"
             height="<?= /* @noEscape */ $block->getIconHeight() ?>"
        >
    </td>
    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">

        <?php if (!$block->isPending()): ?>
            <form class="form" action="<?=
                $block->escapeUrl($block->getUrl('swarming_subscribepro/cards/edit')) ?>" method="get">
                <input name="<?= /** @noEscape */ PaymentTokenInterface::PUBLIC_HASH?>"
                       value="<?= /** @noEscape */ $block->getToken()->getPublicHash() ?>"
                       type="hidden"/>

                <button type="submit" class="action edit">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </button>
            </form>
        <?php endif; ?>

        <form
            class="form"
            action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
            method="post"
        >
            <?= $block->getBlockHtml('formkey')?>
            <input
                name="<?= /** @noEscape */ PaymentTokenInterface::PUBLIC_HASH?>"
                value="<?= /** @noEscape */ $block->getToken()->getPublicHash() ?>"
                type="hidden"/>

            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                                    "Magento_Vault/js/customer_account/deleteWidget":{
                                        "type": "popup",
                                        "modalClass": "my-credit-cards-popup",
                                        "toggleEvent": "click",
                                        "title": "<?= $block->escapeHtml(__('Delete')) ?>",
                                        "content": "Are you sure you want to delete this card: <?=
                                            /** @noEscape */ $ccNumberView ?>?"
                                    }
                                }'>
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
