<?php
/** @var \Swarming\SubscribePro\Block\Vault\Edit $block */
?>
<form class="form-address-edit form-vault-edit"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="vault-edit"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">

    <?= /** @noEscape */ $block->renderBillingAddress() ?>

    <?= /** @noEscape */ $block->renderCard() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-vault"
                    title="<?= $block->escapeHtml(__('Save Card')) ?>">
                <span><?= $block->escapeHtml(__('Save Card')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?=
            $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#vault-edit": {
            "validation": {}
        }
    }
</script>
