<?php
/**
 * @var $block \Swarming\SubscribePro\Block\Vault\Edit
 */
?>
<form class="form-address-edit form-vault-edit"
      action="<?php echo $block->getSaveUrl() ?>"
      method="post"
      id="vault-edit"
      enctype="multipart/form-data"
      data-hasrequired="<?php echo __('* Required Fields') ?>">

    <?php echo $block->renderBillingAddress() ?>

    <?php echo $block->renderCard() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-vault" title="<?php echo __('Save Card') ?>">
                <span><?php echo __('Save Card') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#vault-edit": {
            "validation": {}
        }
    }
</script>
