<?php
/**
 * @var $block \Swarming\SubscribePro\Block\Customer\Subscriptions
 */
?>

<div id="subscriptions-container" data-bind="scope: 'subscriptions-container'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
        }
    }
</script>

<script>
    window.customerData = <?php echo \Zend_Json::encode($block->getCustomerData()); ?>;
</script>
