<?php
/** @var \Swarming\SubscribePro\Block\Customer\Subscriptions $block */
?>
<?php if ($block->isHostedWidgetEnabled() && false !== $block->getPlatformCustomerId()): ?>
    <div id="sp-my-subscriptions" class="sp-my-subscriptions"></div>
    <script src="<?= $block->escapeUrl($block->getHostedWidgetUrl()) ?>"></script>
    <script>
        // Start with override-able defaults
        let finalWidgetConfig = {
            themeName: "base",
            element: "sp-my-subscriptions"
        };
        // Merge in custom configuration
        let customWidgetConfig = <?= /** @noEscape */ $block->getHostedWidgetConfig() ?>;
        for (let key in customWidgetConfig) {
            finalWidgetConfig[key] = customWidgetConfig[key];
        }

        // Don't override the required widget config
        let originalWidgetConfig = {
            apiBaseUrl: "<?= $block->escapeUrl($block->getSubscribeProBaseApiUrl()) ?>",
            apiAccessToken: "<?= /** @noEscape */ $block->getWidgetAccessTokenForCurrentCustomer() ?>",
            customerId: <?= /** @noEscape */ $block->getPlatformCustomerId() ?>
        };
        for (let key in originalWidgetConfig) {
            finalWidgetConfig[key] = originalWidgetConfig[key];
        }

        MySubscriptions.init(finalWidgetConfig);
    </script>
<?php else: ?>
    <div id="subscriptions-container" data-bind="scope: 'subscriptions-container'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>

<script>
    window.customerData = <?= \Zend_Json::encode($block->getCustomerData()) ?>;
</script>
