<?php
/** @var \Swarming\SubscribePro\Block\Adminhtml\System\Config\TestConnection $block */
?>
<div class="actions actions-test-connection">
    <button onclick="testConnection(); return false;
        " class="action-test-connection" type="button" id="<?= $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    &nbsp;
    <span id="test-connection-result" class="message-test-connection"></span>
</div>
<script>
    require(['jquery'], function ($) {
        window.testConnection = function () {

            $('body').trigger('processStart');

            var resultMessageBox = $('#test-connection-result');

            resultMessageBox
                .removeClass('success')
                .removeClass('fail')
                .css('color', '')
                .text('');

            var baseUrl = $('#<?= /** @noEscape */ $block->getBaseUrlSelectorId() ?>').val();
            var clientId = $('#<?= /** @noEscape */ $block->getClientIdSelectorId() ?>').val();
            var clientSecret = $('#<?= /** @noEscape */ $block->getClientSecretSelectorId() ?>').val();

            $.getJSON(
                '<?= $block->escapeUrl($block->getAjaxUrl()) ?>',
                {
                    base_url: baseUrl,
                    client_id: clientId,
                    client_secret: clientSecret,
                    website: '<?= $block->escapeJs($block->getWebsiteCode()) ?>'
                })
                .done(function (result) {
                    console.log(result);
                    resultMessageBox
                        .addClass(result.status)
                        .css('color', (result.status == 'success' ? 'green' : 'red'))
                        .text(result.message);
                })
                .fail(function () {
                    resultMessageBox
                        .addClass('fail')
                        .css('color', 'red')
                        .text($.mage.__('An error occurred while request.'));
                })
                .always(function () {
                    $('body').trigger('processStop');
                });
        };
    })
</script>
