<?php
/**
 * @var $block \Swarming\SubscribePro\Block\Vault\Edit\BillingAddress
 */
?>
<fieldset class="fieldset">
    <legend class="legend"><span><?php echo __('Contact Information') ?></span></legend><br>
    <?php echo $block->getBlockHtml('formkey')?>
    <div class="field field-name-firstname required">
        <label class="label" for="first_name"><span><?php echo __('First Name') ?></span></label>
        <div class="control">
            <input type="text" id="first_name" name="billing_address[first_name]" class="input-text required-entry" data-validate="{required:true}"
                   value="<?php echo $block->escapeHtml($block->getFirstName()) ?>"
                   title="<?php echo __('First Name') ?>">
        </div>
    </div>
    <div class="field field-name-middlename">
        <label class="label"  for="middle_name"><span><?php echo __('Middle Name') ?></span></label>
        <div class="control">
            <input type="text" id="middle_name" name="billing_address[middle_name]" class="input-text"
                   value="<?php echo $block->escapeHtml($block->getMiddleName()) ?>"
                   title="<?php echo __('Middle Name') ?>">
        </div>
    </div>
    <div class="field field-name-lastname required">
        <label class="label"  for="last_name"><span><?php echo __('Last Name') ?></span></label>
        <div class="control">
            <input type="text" id="last_name" name="billing_address[last_name]" class="input-text required-entry" data-validate="{required:true}"
                   value="<?php echo $block->escapeHtml($block->getLastName()) ?>"
                   title="<?php echo __('Last Name') ?>">
        </div>
    </div>
    <div class="field field-name-company">
        <label class="label"  for="company"><span><?php echo __('Company') ?></span></label>
        <div class="control">
            <input type="text" id="company" name="billing_address[company]" class="input-text"
                   value="<?php echo $block->escapeHtml($block->getCompany()) ?>"
                   title="<?php echo __('Company') ?>">
        </div>
    </div>
    <div class="field telephone required">
        <label class="label" for="telephone"><span><?php echo __('Phone Number') ?></span></label>
        <div class="control">
            <input type="text" id="telephone" name="billing_address[phone]" class="input-text required-entry" data-validate="{required:true}"
                   value="<?php echo $block->escapeHtml($block->getTelephone()) ?>"
                   title="<?php echo __('Phone Number') ?>">
        </div>
    </div>
</fieldset>

<fieldset class="fieldset">
    <legend class="legend"><span><?php echo __('Address') ?></span></legend><br>
    <div class="field street required">
        <label for="street1" class="label"><span><?php echo __('Street Address') ?></span></label>
        <div class="control">
            <input type="text" name="billing_address[street1]" id="street1" class="input-text required-entry"
                   value="<?php echo $block->escapeHtml($block->getStreetLine1()) ?>"
                   title="<?php echo __('Street Address') ?>" />
            <div class="nested">
                <div class="field additional">
                    <label class="label" for="street2"><span><?php echo __('Street Address 2') ?></span></label>
                    <div class="control">
                        <input type="text" name="billing_address[street2]" id="street2" class="input-text"
                               value="<?php echo $block->escapeHtml($block->getStreetLine2()) ?>"
                               title="<?php echo __('Street Address 2') ?>">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="field city required">
        <label class="label" for="city"><span><?php echo __('City') ?></span></label>
        <div class="control">
            <input type="text" name="billing_address[city]" class="input-text required-entry" id="city"
                   value="<?php echo $block->escapeHtml($block->getCity()) ?>"
                   title="<?php echo __('City') ?>">
        </div>
    </div>
    <div class="field region required">
        <label class="label" for="region_id"><span><?php echo __('State/Province') ?></span></label>
        <div class="control">
            <select id="region_id" name="billing_address[region_id]"
                    title="<?php echo __('State/Province') ?>"
                    class="validate-select" <?php echo(!$block->getIsRegionDisplayAll()) ? ' disabled="disabled"' : '';?>>
                <option value=""><?php echo __('Please select a region, state or province.') ?></option>
            </select>
            <input type="text" id="region" name="billing_address[region]"
                   value="<?php echo $block->escapeHtml($block->getRegion()) ?>"
                   title="<?php echo __('State/Province') ?>"
                   class="input-text"<?php echo(!$block->getIsRegionDisplayAll()) ? ' disabled="disabled"' : '';?>/>
        </div>
    </div>
    <div class="field zip required">
        <label class="label" for="postcode"><span><?php echo __('Zip/Postal Code') ?></span></label>
        <div class="control">
            <input type="text" name="billing_address[postcode]" id="postcode" class="input-text validate-zip-international"
                   value="<?php echo $block->escapeHtml($block->getPostCode()) ?>"
                   title="<?php echo __('Zip/Postal Code') ?>" >
        </div>
    </div>
    <div class="field country required">
        <label class="label" for="country"><span><?php echo __('Country') ?></span></label>
        <div class="control">
            <?php echo $block->getCountryHtmlSelect(null, 'billing_address[country]') ?>
        </div>
    </div>
</fieldset>

<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php echo($block->getIsRegionDisplayAll() ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#postcode",
                "form": "#vault-edit",
                "regionJson": <?php echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
