<?php
/** @var \Swarming\SubscribePro\Block\Vault\Edit\BillingAddress $block */
?>
<fieldset class="fieldset">
    <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend><br>
    <?= $block->getBlockHtml('formkey')?>
    <div class="field field-name-firstname required">
        <label class="label" for="first_name"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
        <div class="control">
            <input type="text" id="first_name" name="billing_address[first_name]" class="input-text required-entry"
                   data-validate="{required:true}"
                   value="<?= $block->escapeHtmlAttr($block->getFirstName()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('First Name')) ?>">
        </div>
    </div>
    <div class="field field-name-middlename">
        <label class="label"  for="middle_name"><span><?= $block->escapeHtml(__('Middle Name')) ?></span></label>
        <div class="control">
            <input type="text" id="middle_name" name="billing_address[middle_name]" class="input-text"
                   value="<?= $block->escapeHtmlAttr($block->getMiddleName()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('Middle Name')) ?>">
        </div>
    </div>
    <div class="field field-name-lastname required">
        <label class="label"  for="last_name"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
        <div class="control">
            <input type="text" id="last_name" name="billing_address[last_name]" class="input-text required-entry"
                   data-validate="{required:true}"
                   value="<?= $block->escapeHtmlAttr($block->getLastName()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>">
        </div>
    </div>
    <div class="field field-name-company">
        <label class="label"  for="company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
        <div class="control">
            <input type="text" id="company" name="billing_address[company]" class="input-text"
                   value="<?= $block->escapeHtmlAttr($block->getCompany()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('Company')) ?>">
        </div>
    </div>
    <div class="field telephone required">
        <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
        <div class="control">
            <input type="text" id="telephone" name="billing_address[phone]" class="input-text required-entry"
                   data-validate="{required:true}"
                   value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>">
        </div>
    </div>
</fieldset>

<fieldset class="fieldset">
    <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend><br>
    <div class="field street required">
        <label for="street1" class="label"><span><?= $block->escapeHtml(__('Street Address')) ?></span></label>
        <div class="control">
            <input type="text" name="billing_address[street1]" id="street1" class="input-text required-entry"
                   value="<?= $block->escapeHtmlAttr($block->getStreetLine1()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" />
            <div class="nested">
                <div class="field additional">
                    <label class="label" for="street2">
                        <span><?= $block->escapeHtml(__('Street Address 2')) ?></span></label>
                    <div class="control">
                        <input type="text" name="billing_address[street2]" id="street2" class="input-text"
                               value="<?= $block->escapeHtmlAttr($block->getStreetLine2()) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Street Address 2')) ?>">
                    </div>
                </div>
            </div>
            <div class="nested">
                <div class="field additional">
                    <label class="label" for="street3">
                        <span><?= $block->escapeHtml(__('Street Address 3')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="billing_address[street3]" id="street3" class="input-text"
                               value="<?= $block->escapeHtmlAttr($block->getStreetLine3()) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Street Address 3')) ?>">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="field city required">
        <label class="label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
        <div class="control">
            <input type="text" name="billing_address[city]" class="input-text required-entry" id="city"
                   value="<?= $block->escapeHtmlAttr($block->getCity()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('City')) ?>">
        </div>
    </div>
    <div class="field region required">
        <label class="label" for="region_id"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
        <div class="control">
            <select id="region_id" name="billing_address[region_id]"
                    title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                    class="validate-select" <?=(!$block->getIsRegionDisplayAll()) ? ' disabled="disabled"' : '';?>>
                <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
            </select>
            <input type="text" id="region" name="billing_address[region]"
                   value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                   class="input-text"<?= (!$block->getIsRegionDisplayAll()) ? ' disabled="disabled"' : '' ?>/>
        </div>
    </div>
    <div class="field zip required">
        <label class="label" for="postcode"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
        <div class="control">
            <input type="text" name="billing_address[postcode]" id="postcode"
                   class="input-text validate-zip-international"
                   value="<?= $block->escapeHtmlAttr($block->getPostCode()) ?>"
                   title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>" >
        </div>
    </div>
    <div class="field country required">
        <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
        <div class="control">
            <?= $block->getCountryHtmlSelect(null, 'billing_address[country]') ?>
        </div>
    </div>
</fieldset>

<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= ($block->getIsRegionDisplayAll() ? 'true' : 'false') ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#postcode",
                "form": "#vault-edit",
                "regionJson": <?=
                    // phpcs:ignore Magento2.Templates.ThisInTemplate.FoundHelper
                    /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?=
                    // phpcs:ignore Magento2.Templates.ThisInTemplate.FoundHelper
                    /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)
                                        ->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
