<?php
/** @var \Swarming\SubscribePro\Block\Vault\Edit\CardExpiration $block */
?>
<fieldset class="fieldset" data-bind="scope: 'subscribe-pro-vault-card-expiration'">
    <legend class="legend"><span><?= $block->escapeHtml(__('Payment Information')) ?></span></legend><br>

    <div class="card-number-type">
        <img src="<?= /* @noEscape */ $block->getIconUrl() ?>"
             width="<?= /* @noEscape */ $block->getIconWidth() ?>"
             height="<?= /* @noEscape */ $block->getIconHeight() ?>">
        <span><?= $block->escapeHtml(__('ending')) ?> <?= $block->escapeHtml($block->getNumberLast4Digits()) ?></span>
    </div>

    <div class="field date required expiration-date">
        <label for="creditcard_month" class="label">
            <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="control">
            <div class="date-wrap">
                <div class="child-control month">
                    <input type="text"
                           name="creditcard_month"
                           data-bind="attr: {id: getCode() + '_expiration'},
                               value: creditCardExpMonth,
                               hasFocus: creditCardExpMonthFocus"
                           size="3"
                           maxlength="2"
                           placeholder="MM"
                           class="input-text required-entry validate-expiration-date"
                           autocomplete="off"
                           value="<?= $block->escapeHtmlAttr($block->getExpirationMonth()) ?>"
                    >
                </div>
                <div class="child-control year">
                    <input type="text"
                           name="creditcard_year"
                           data-bind="attr: {id: getCode() + '_expiration_yr'},
                               value: creditCardExpYear,
                               hasFocus: creditCardExpYearFocus"
                           size="5"
                           maxlength="4"
                           placeholder="YYYY"
                           class="input-text required-entry"
                           autocomplete="off"
                           value="<?= $block->escapeHtmlAttr($block->getExpirationYear()) ?>"
                    >
                </div>
                <div class="error"><!-- ko i18n: 'Please, enter valid Expiration Date'--><!-- /ko --></div>
            </div>
        </div>
    </div>
</fieldset>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>
