<?php
/** @var \Swarming\SubscribePro\Block\Vault\Edit\Card $block */
?>
<div data-bind="scope: 'subscribe-pro-vault-card'" class="checkout-payment-method subscribe-pro-vault-card">
    <div data-bind="blockLoader: isLoading">
        <!-- ko template: 'Swarming_SubscribePro/payment/cc-fieldset' --><!-- /ko -->
        <!-- ko template: 'Swarming_SubscribePro/payment/three-ds' --><!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>
<script>
    window.subscribeProPaymentConfig = <?= /** @noEscape */ $block->getPaymentConfig() ?>;
</script>
<?php if ($block->isWalletAuthorizationActive()): ?>
    <div class="wallet-authorize-info"><?= $block->escapeHtml(__(
        'You may see a %amount pre-authorization on your credit card account.',
        ['amount' => $block->getWalletAuthorizationAmount()]
    )) ?></div>
<?php endif; ?>
