<?php
/**
 * @var $block \Swarming\SubscribePro\Block\Vault\Edit\CreateCard
 */
?>
<fieldset class="fieldset checkout-payment-method subscribe-pro-vault-card-create" data-bind="scope: 'subscribe-pro-vault-card-create'">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Payment Information') ?></span></legend><br>

    <div class="field type">
        <div class="control">
            <ul class="credit-card-types">
                <!-- ko foreach: {data: getCcAvailableTypesValues(), as: 'item'} -->
                <li class="item" data-bind="css: {
                                                 _active: $parent.selectedCardType() == item.value,
                                                 _inactive: $parent.selectedCardType() != null && $parent.selectedCardType() != item.value
                                                 } ">
                    <!--ko if: $parent.getIcons(item.value) -->
                    <img data-bind="attr: {
                        'src': $parent.getIcons(item.value).url,
                        'alt': item.type,
                        'width': $parent.getIcons(item.value).width,
                        'height': $parent.getIcons(item.value).height
                        }">
                    <!--/ko-->
                </li>
                <!--/ko-->
            </ul>
            <input type="hidden"
                   name="payment[cc_type]"
                   class="input-text"
                   value=""
                   data-bind="attr: {id: getCode() + '_cc_type', 'data-container': getCode() + '-cc-type'},
                   value: creditCardType
                   ">
        </div>
    </div>

    <div class="field number required">
        <label data-bind="attr: {for: getCode() + '_cc_number'}" class="label">
            <span><!-- ko i18n: 'Credit Card Number'--><!-- /ko --></span>
        </label>
        <div class="control">
            <div data-bind="attr: {id: getCode() + '_cc_number'}" class="hosted-control"></div>
            <div class="hosted-error"><!-- ko i18n: 'Please, enter valid Credit Card Number'--><!-- /ko --></div>
        </div>
        <input type="hidden" name="payment[token]" data-bind="attr: {id: getCode() + '_token'}, value: paymentMethodToken">
    </div>

    <div class="field date required" data-bind="attr: {id: getCode() + '_cc_type_exp_div'}">
        <label data-bind="attr: {for: getCode() + '_expiration'}" class="label">
            <span><!-- ko i18n: 'Expiration Date'--><!-- /ko --></span>
        </label>
        <div class="control">
            <div class="date-wrap">
                <div class="child-control month">
                    <input type="text"
                           name="payment[cc_exp_month]"
                           data-bind="attr: {id: getCode() + '_expiration'}, value: creditCardExpMonth, hasFocus: creditCardExpMonthFocus"
                           size="3"
                           maxlength="2"
                           placeholder="MM",
                           autocomplete="off"
                    >
                </div>
                <div class="child-control year">
                    <input type="text"
                           name="payment[cc_exp_year]"
                           data-bind="attr: {id: getCode() + '_expiration_yr'}, value: creditCardExpYear, hasFocus: creditCardExpYearFocus"
                           size="5"
                           maxlength="4"
                           placeholder="YYYY"
                           autocomplete="off"
                    >
                </div>
                <div class="error"><!-- ko i18n: 'Please, enter valid Expiration Date'--><!-- /ko --></div>
            </div>
        </div>
    </div>

    <!-- ko if: (hasVerification())-->
    <div class="field cvv required" data-bind="attr: {id: getCode() + '_cc_type_cvv_div'}">
        <label data-bind="attr: {for: getCode() + '_cc_cid'}" class="label">
            <span><!-- ko i18n: 'Card Verification Number'--><!-- /ko --></span>
        </label>
        <div class="control _with-tooltip">
            <div data-bind="attr: {id: getCode() + '_cc_cid'}" class="hosted-control hosted-cid"></div>
            <div class="hosted-error"><!-- ko i18n: 'Please, enter valid Card Verification Number'--><!-- /ko --></div>

            <div class="field-tooltip toggle">
                            <span class="field-tooltip-action action-cvv"
                                  tabindex="0"
                                  data-toggle="dropdown"
                                  data-bind="attr: {title: $t('What is this?')}, mageInit: {'dropdown':{'activeClass': '_active'}}">
                                <span><!-- ko i18n: 'What is this?'--><!-- /ko --></span>
                            </span>
                <div class="field-tooltip-content"
                     data-target="dropdown"
                     data-bind="html: getCvvImageHtml()"></div>
            </div>
        </div>
    </div>
    <!-- /ko -->

    <!-- ko if: (initSpreedly()) --><!-- /ko -->
</fieldset>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }
    }
</script>
<script>
    window.subscribeProPaymentConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getPaymentConfig()); ?>;
</script>
<style>
    /* TODO temporary solution, just for dev testing */
    .subscribe-pro-vault-card-create .hosted-control {
        background: #fff;
        background-clip: padding-box;
        border: 1px solid #c2c2c2;
        border-radius: 1px;
        font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-size: 14px;
        height: 32px;
        line-height: 1.42857143;
        padding: 0 9px;
        vertical-align: baseline;
        box-sizing: border-box;
        position: relative;
        width: 225px;
    }

    .subscribe-pro-vault-card-create .child-control.control-focused input,
    .subscribe-pro-vault-card-create .hosted-control.hosted-control-focused {
        border-color: #006bb4;
    }

    .subscribe-pro-vault-card-create .child-control.control-valid input,
    .subscribe-pro-vault-card-create .hosted-control.hosted-control-valid {
        border-color: #006400;
    }

    .subscribe-pro-vault-card-create .child-control.control-invalid:not(.control-focused) input,
    .subscribe-pro-vault-card-create .hosted-control.hosted-control-invalid:not(.hosted-control-focused) {
        border-color: #e02b27;
    }

    .subscribe-pro-vault-card-create .control-invalid:not(.control-focused) ~ .error,
    .subscribe-pro-vault-card-create .hosted-control-invalid:not(.hosted-control-focused) ~ .hosted-error {
        opacity: 1;
    }

    .subscribe-pro-vault-card-create .hosted-control.hosted-cid {
        width: 6rem;
    }

    .subscribe-pro-vault-card-create .cvv .field-tooltip {
        left: 7rem;
    }

    .subscribe-pro-vault-card-create .error,
    .subscribe-pro-vault-card-create .hosted-error {
        clear: both;
        color: #e02b27;
        font-size: 1.2rem;
        height: 0;
        margin-top: 7px;
        opacity: 0;
    }

    .subscribe-pro-vault-card-create .date-wrap .child-control{
        float: left;
        margin-right: 2rem;
    }

    .subscribe-pro-vault-card-create .date-wrap input:focus{
        outline: none;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    .subscribe-pro-vault-card-create .date-wrap .month{
        position: relative;
    }
    .subscribe-pro-vault-card-create .date-wrap .month:after{
        content: '/';
        display: inline;
        padding-bottom: inherit;
        padding-top: inherit;
        position: absolute;
        right: -12px;
        top: 5px;
    }
</style>
