<?php
/**
 * @var $block \Swarming\SubscribePro\Block\Vault\Edit\Card
 */
?>
<div data-bind="scope: 'subscribe-pro-vault-card'" class="checkout-payment-method subscribe-pro-vault-card">
    <!-- ko template: 'Swarming_SubscribePro/payment/cc-fieldset' --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
        }
    }
</script>
<script>
    window.subscribeProPaymentConfig = <?php echo $block->getPaymentConfig(); ?>;
</script>