<?php
/**
 * @var $block \Swarming\SubscribePro\Block\Vault\Edit\Card
 */
?>
<div data-bind="scope: 'subscribe-pro-vault-card'" class="checkout-payment-method subscribe-pro-vault-card">
    <!-- ko template: 'Swarming_SubscribePro/payment/cc-fieldset' --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }
    }
</script>
<script>
    window.subscribeProPaymentConfig = <?php /* @escapeNotVerified */ echo $block->getPaymentConfig(); ?>;
</script>
<style>
    /* TODO temporary solution, just for dev testing */

    .subscribe-pro-vault-card fieldset {
        float: none !important;
    }

    .subscribe-pro-vault-card .legend {
        clip: auto !important;
        position: inherit !important;
        margin: 0 0 20px !important;
        padding: 0 0 10px !important;
        box-sizing: border-box !important;
        font-weight: 300 !important;
        line-height: 1.2 !important;
        font-size: 1.8rem !important;
        border-bottom: 1px solid #c6c6c6 !important;
        width: 100% !important;
        height: auto !important;
    }

    .subscribe-pro-vault-card .hosted-control {
        background: #fff;
        background-clip: padding-box;
        border: 1px solid #c2c2c2;
        border-radius: 1px;
        font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-size: 14px;
        height: 32px;
        line-height: 1.42857143;
        padding: 0 9px;
        vertical-align: baseline;
        box-sizing: border-box;
        position: relative;
        width: 225px;
    }

    .subscribe-pro-vault-card .child-control.control-focused input,
    .subscribe-pro-vault-card .hosted-control.hosted-control-focused {
        border-color: #006bb4;
    }

    .subscribe-pro-vault-card .child-control.control-valid input,
    .subscribe-pro-vault-card .hosted-control.hosted-control-valid {
        border-color: #006400;
    }

    .subscribe-pro-vault-card .child-control.control-invalid:not(.control-focused) input,
    .subscribe-pro-vault-card .hosted-control.hosted-control-invalid:not(.hosted-control-focused) {
        border-color: #e02b27;
    }

    .subscribe-pro-vault-card .control-invalid:not(.control-focused) ~ .error,
    .subscribe-pro-vault-card .hosted-control-invalid:not(.hosted-control-focused) ~ .hosted-error {
        opacity: 1;
    }

    .subscribe-pro-vault-card .hosted-control.hosted-cid {
        width: 6rem;
    }

    .subscribe-pro-vault-card .cvv .field-tooltip {
        left: 7rem;
    }

    .subscribe-pro-vault-card .error,
    .subscribe-pro-vault-card .hosted-error {
        clear: both;
        color: #e02b27;
        font-size: 1.2rem;
        height: 0;
        margin-top: 7px;
        opacity: 0;
    }

    .subscribe-pro-vault-card .date-wrap .child-control{
        float: left;
        margin-right: 2rem;
    }

    .subscribe-pro-vault-card .date-wrap input:focus{
        outline: none;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    .subscribe-pro-vault-card .date-wrap .month{
        position: relative;
    }
    .subscribe-pro-vault-card .date-wrap .month:after{
        content: '/';
        display: inline;
        padding-bottom: inherit;
        padding-top: inherit;
        position: absolute;
        right: -12px;
        top: 5px;
    }
</style>
